#!/usr/bin/bash

# ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
#  _                                 
# | |                                
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           | |                      
#           |_|                      
#
# ===== ===== ===== ===== ===== ===== ===== ===== ===== =====

colors() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
pgrep -x dunst > /dev/null || dunst &
pgrep -x polybar > /dev/null || polybar bar &
pgrep -x blueman-applet > /dev/null || blueman-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap					 5

bspc config focused_border_color $(colors color10)
bspc config normal_border_color $(colors background)
bspc config urgent_border_color $(colors color1)
bspc config presel_feedback_color $(colors color3)

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Blueman-manager state=floating

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
